#!/usr/bin/env node
/**
 * Copy the shared pieces out of the desktop app into the phone bundle.
 *
 * Three files are shared and none of them are forked: the relay protocol, the realtime
 * page, and the WebRTC logic inside it. Copying rather than reimplementing is the whole
 * point — the turn-gating in `rtc.js` is the fix for the orchestrator answering the same
 * question three times, and a second hand-written copy would be a second place for that
 * to come back.
 *
 * Run automatically before every Capacitor sync. If this stops running, the phone drifts
 * silently: it would still connect, still talk, and slowly disagree with the desk about
 * the protocol.
 *
 *   node sync.mjs
 */
import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ember = join(here, '..')
const www = join(here, 'www')
mkdirSync(www, { recursive: true })

const copies = [
  ['resources/relay/protocol.js', 'protocol.js'],
  ['resources/realtime/rtc.js', 'rtc.js'],
  // 3.5MB, and the reason the APK is not 500KB. Worth it: a diagram is the thing most
  // worth seeing on a phone, and the alternative is fetching it from a bridge the phone
  // has no route to. renderPanelDocument rewrites the script path for this copy.
  ['resources/vendor/mermaid.min.js', 'mermaid.min.js'],
]

for (const [from, to] of copies) {
  copyFileSync(join(ember, from), join(www, to))
  console.log(`  ${from} -> www/${to}`)
}

// The realtime page needs one change and exactly one: the desktop serves its script from
// a bridge route, and here it sits beside the page. Rewritten rather than kept as a
// second file so the rest of it — the audio element, the styles that make the frame
// invisible — stays identical.
const page = readFileSync(join(ember, 'resources/realtime.html'), 'utf8').replace(
  '/realtime/rtc.js',
  'rtc.js'
)
if (!page.includes('src="rtc.js"')) {
  console.error('! the realtime page did not contain the script path this expected')
  process.exit(1)
}
writeFileSync(join(www, 'realtime.html'), page, 'utf8')
console.log('  resources/realtime.html -> www/realtime.html (script path rewritten)')

console.log('synced')

/**
 * Bake this machine's account into the bundle.
 *
 * The phone should know the user's machines the moment it is installed — no code to scan, no
 * code to paste. Since the APK is built here, on a machine that is already on the account,
 * the key can simply travel with it.
 *
 * THAT MAKES THE APK A CREDENTIAL. Anyone who gets the file can reach every machine on the
 * account. It belongs in his own Drive and nowhere else, and it must never be handed to
 * anyone — the ordinary instinct to share an APK is exactly the wrong one here.
 *
 * If no account exists on this machine, the file is written empty and the app falls back
 * to asking to join one. That path still has to work: it is what a second phone uses, and
 * what any build made on a machine that has not joined yet produces.
 */
const accountFile = join(process.env.USERPROFILE ?? process.env.HOME ?? '', '.ember', 'account.json')
let baked = null
try {
  if (existsSync(accountFile)) {
    const a = JSON.parse(readFileSync(accountFile, 'utf8'))
    if (a.key) baked = { relay: a.relay, key: a.key }
  }
} catch {
  /* an unreadable account file is the same as not having one */
}

writeFileSync(
  join(www, 'account.js'),
  `// Generated by sync.mjs — do not edit, do not commit, do not share this build.\n` +
    `export const BAKED = ${JSON.stringify(baked)}\n`,
  'utf8'
)
console.log(baked ? `  baked in the account on this machine (${new URL(baked.relay).host})` : '  no account on this machine — the app will ask to join one')
